name: Build and Test Android App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test: # Saya ganti nama job menjadi 'test' agar lebih deskriptif
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [29] # Anda bisa menambahkan API level lain di sini, misal: [29, 30, 31]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # ==========================================================
      # FIX #1: Menambahkan langkah ini untuk memberi izin eksekusi
      # ==========================================================
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          # ==========================================================
          # FIX #2: Menghapus `:app:` dari perintah script
          # ==========================================================
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload test reports
        # 'always()' memastikan laporan tetap diunggah meskipun test gagal
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.api-level }}
          # ==========================================================
          # FIX #3: Menghapus `app/` dari path laporan
          # ==========================================================
          path: ./build/reports/androidTests/
